
accountTabButton = "accountTabButton"
login_input  = "loginUsernameInput"
password_input = "loginPasswordInput"
login_password_input_id = "loginPasswordInput"
log_sbmt_btn = "//*[@id=\"loginButton\"]/span"
deposit_btn = "//*[@id=\"depositHeaderButtonLink\"]" 

footbal_section =     "//*[@id=\"nav-football\"]/a"
competite_section =    "//*[@id=\"nav-football-competitions\"]"
win_home_1st_row =     "//div[@class=\"market-group marketW win-draw-win events-group-container\"]/section/div[2]/div[1]/div[2]/div[1]/button"
bet_input =       "//div[@class=\"betslip-selection__stake-container betslip-selection__stake-container--single\"]/span/input"
odds_element =     "//span[@class=\"betslip-selection__price\"]"
returns_1 =       "//div[@class=\"betslip-selection__estimated-returns\"]/span/span"
returns_2 =       "//span[@id=\"total-to-return-price\"]"